// This file is automatically generated - edits will be lost!
'use server';

/**
 * @fileOverview Flow for improving the quality of a generated story by correcting grammar and style.
 *
 * - improveStoryQuality - A function that takes a story and improves its grammar and style.
 * - ImproveStoryQualityInput - The input type for the improveStoryQuality function.
 * - ImproveStoryQualityOutput - The return type for the improveStoryQuality function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveStoryQualityInputSchema = z.object({
  story: z.string().describe('The story to improve.'),
});
export type ImproveStoryQualityInput = z.infer<typeof ImproveStoryQualityInputSchema>;

const ImproveStoryQualityOutputSchema = z.object({
  improvedStory: z.string().describe('The improved story with better grammar and style.'),
});
export type ImproveStoryQualityOutput = z.infer<typeof ImproveStoryQualityOutputSchema>;

export async function improveStoryQuality(input: ImproveStoryQualityInput): Promise<ImproveStoryQualityOutput> {
  return improveStoryQualityFlow(input);
}

const improveStoryQualityPrompt = ai.definePrompt({
  name: 'improveStoryQualityPrompt',
  input: {schema: ImproveStoryQualityInputSchema},
  output: {schema: ImproveStoryQualityOutputSchema},
  prompt: `You are an AI that improves the grammar and style of a given story.

  Please review the following story and correct any grammar or style issues, and return the improved story.

  Story: {{{story}}}`,
});

const improveStoryQualityFlow = ai.defineFlow(
  {
    name: 'improveStoryQualityFlow',
    inputSchema: ImproveStoryQualityInputSchema,
    outputSchema: ImproveStoryQualityOutputSchema,
  },
  async input => {
    const {output} = await improveStoryQualityPrompt(input);
    return output!;
  }
);
